name: qmuli
version: "0.0.1"
synopsis: EDSL for building infrastructure on AWS
description: EDSL for building infrastructure on AWS
category: AWS, Cloud
maintainer: Alex Babkin
stability: experimental
license: MIT
license-file: LICENSE.md

github: qmuli/qmuli

extra-source-files:
  - CHANGELOG.md
  - README.md
  - stack.yaml

dependencies:
  - base >= 4.8 && < 5
  - aeson >= 0.11.2.1
  - data-default
  - directory
  - unix
  - text
  - transformers
  - mtl
  - operational
  - bytestring
  - hashable
  - unordered-containers
  - lens
  - stratosphere
  - amazonka
  - amazonka-core
  - amazonka-s3
  - amazonka-cloudformation
  - amazonka-dynamodb
  - conduit
  - conduit-extra
  - resourcet
  - turtle
  - executable-path
  - heredoc
  - system-extra
  - process
  # - groundhog
  # - groundhog-th
  # - groundhog-sqlite

library:
  source-dirs:
    - src
  ghc-options: -Wall

executables:
  simple-s3-copy:
    main: Main.hs
    source-dirs: examples/simple-s3-copy/src
    dependencies:
      - base >= 4.8 && < 5
      - qmuli
    ghc-options: -Wall -static -threaded -rtsopts -with-rtsopts=-N
  apigw-lambda-s3:
    main: Main.hs
    source-dirs: examples/apigw-lambda-s3/src
    dependencies:
      - base >= 4.8 && < 5
      - qmuli
    ghc-options: -Wall -static -threaded -rtsopts -with-rtsopts=-N
  apigw-lambda-dynamodb:
    main: Main.hs
    source-dirs: examples/apigw-lambda-dynamodb/src
    dependencies:
      - base >= 4.8 && < 5
      - qmuli
    ghc-options: -Wall -static -threaded -rtsopts -with-rtsopts=-N
  # apigw-lambda-rds:
    # main: Main.hs
    # source-dirs: examples/apigw-lambda-rds/src
    # dependencies:
      # - base >= 4.8 && < 5
      # - qmuli
      # - groundhog
      # - groundhog-th
      # - groundhog-sqlite
    # ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N

tests:
  tasty:
    main: Main.hs
    source-dirs:
      - tests
    dependencies:
      - base
      - qmuli
      - stratosphere
      - tasty
      - tasty-hspec
