#resolver: lts-11.3
resolver: nightly-2018-01-01



packages:
- '.'
- location:
    git: https://github.com/frontrowed/stratosphere.git
    commit: 1df7b9b215c231d0e3b93e81ed3dcc842d887c78
  extra-dep: true

- location:
    git: https://github.com/abailly/system-extra.git
    commit: 6223138579dc3473cbf84fa323af64380db114cf
  extra-dep: true
    
- location:
    git: https://github.com/ababkin/amazonka-s3-streaming.git
    commit: 4fc25d1b20007bef3b8b2924751fe0fc3033e1f5
  extra-dep: true

extra-deps:
  - aeson-1.3.0.0
  - text-1.2.3.0

flags: {}

extra-package-dbs: []

ghc-options:
  "qmuli": 
    # -O*
    # -funfolding-use-threshold=16 -O2 -optc-O3
    -O
    -Wall
    -Wno-unused-imports 
    -Wno-unused-matches 
    -Wno-unused-do-bind
    -threaded
    -Werror
    #-static 

    # "qmuli-stream-s3-objects": -static -threaded
    # "qmuli-fold-s3-content": -static -threaded
    # "qmuli-apigw-lambda-dynamodb": -static -threaded

apply-ghc-options: locals # all local packages, the default

build:
  library-profiling: false
  executable-profiling: false
  copy-bins: false
  prefetch: false
  keep-going: false


