#resolver: lts-11.7
resolver: nightly-2018-06-02

packages:
- '.'
# - location:
    # git: https://github.com/frontrowed/stratosphere.git
    # commit: 6b9b0748c9a57ce2ea0e642211ee6a13c3cd97f3
  # extra-dep: true
- location:
    git: https://github.com/ababkin/system-extra.git
    commit: 0ec5b3ca62bd73a4df6f29b99b654071a0262f18
  extra-dep: true
  #- location:
  #  git: https://github.com/ababkin/amazonka-s3-streaming.git
  #  commit: 4fc25d1b20007bef3b8b2924751fe0fc3033e1f5
  #extra-dep: true

extra-deps: []
  
flags: {}

extra-package-dbs: []

ghc-options:
  "qmuli": 
    # -O*
    # -funfolding-use-threshold=16 -O2 -optc-O3
    -O0
    -Wall
    -Wno-unused-imports 
    -Wno-unused-matches 
    -Wno-unused-do-bind
    -Wno-deprecations
    -threaded
    -Werror
    #-static 

    # "qmuli-stream-s3-objects": -static -threaded
    # "qmuli-fold-s3-content": -static -threaded
    # "qmuli-apigw-lambda-dynamodb": -static -threaded

apply-ghc-options: locals # all local packages, the default

build:
  library-profiling: false
  executable-profiling: false
  copy-bins: false
  prefetch: false
  keep-going: false


